#! /usr/bin/python2

import ldap, ldap.sasl, sys, re

host = 'ldap://127.0.0.1:389/'

e = '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$'
e = re.compile(e, re.IGNORECASE)

length = len(sys.argv)

error = 'Usage: %s [ shell ]' % sys.argv[0]
if length > 1 and sys.argv[1] == '--help':
  print error; sys.exit(1)
elif length > 2: 
  print error; sys.exit(1)

error = '%s is not a valid RFC 2822 address'
if length == 2 and not e.match(sys.argv[1]):
  print error % ( sys.argv[1] ); sys.exit(1)

connection = ldap.initialize(host)
gssapi = ldap.sasl.gssapi()
connection.sasl_interactive_bind_s('', gssapi)
rootdn = connection.whoami_s()[3:]

if length == 2:
  oper = ldap.MOD_REPLACE; mail = sys.argv[1]
  connection.modify_s(rootdn, [ \
  ( ldap.MOD_REPLACE, 'mail', mail ) ])

scope = ldap.SCOPE_BASE
value = connection.search_s(rootdn, scope)

mail = value[0][1]['mail'][0]
print "Your mail is set to '%s'." % ( mail )
