#! /usr/bin/python2

import ldap, os, sys, re, getpass, string

cookie = os.getenv('HOME') + '/.password'
host = 'ldap://127.0.0.1:389/'

length = len(sys.argv)

error = 'Usage: %s [ file ]' % sys.argv[0]
if length > 1 and sys.argv[1] == '--help':
  print error; sys.exit(1)
elif length > 2:
  print error; sys.exit(1)

binddn = 'cn=%s,ou=people,dc=kiwilight,dc=com'
binddn = binddn % ( \
  getpass.getuser().replace('.', ' ').title())

try: passwd = open(cookie).read().strip()
except IOError:
  passwd = getpass.getpass('Old Password: ')

connection = ldap.initialize(host)
connection.simple_bind_s(binddn, passwd)

password = getpass.getpass('New Password: ')

error = 'The new password entered is invalid.'
if not password: print error; sys.exit(1)
printable = string.printable
if not all(c in printable for c in password):
  print error; sys.exit(1)
connection.passwd_s(binddn, passwd, password)

if length == 2:
  open(sys.argv[1], 'w').write(password)

print 'Your password was successfully changed.'
